---
- name: Deploy Docker application
  hosts: webserver
  become: yes

  tasks:
    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker image
      docker_image:
        name: praveenkumar1131/medicure-application
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: finance_app
        image: praveenkumar1131/medicure-application:latest
        state: started
        restart_policy: always
        ports:
          - "8082:8082"
